name: Update List

on:
  workflow_dispatch:

jobs:
  update_list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run CI
        run: |
          cd ci
          cargo run
