name: Update List

on:
  workflow_dispatch:

jobs:
  update_list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Set current datetime as env variable
        env:
          TZ: "Asia/Tokyo"
        run: echo "CURRENT_DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Create new branch
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git switch -c ci/${{ env.CURRENT_DATETIME }}
          git push -u origin ci/${{ env.CURRENT_DATETIME }}

      - name: Run CI
        run: |
          cd ci
          cargo run

      - name: Add and Commit
        uses: EndBug/add-and-commit@v7
        with:
          branch: ci/${{ env.CURRENT_DATETIME }}
          message: "update list"
          add: "./docs/index.json"

      - name: Create pull request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ci/${{ env.CURRENT_DATETIME }}
          destination_branch: main
          pr_title: "Update List"
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}